include: package:pedantic/analysis_options.1.8.0.yaml
analyzer:
  exclude:
    # Ignore generated files
    - '**/*.g.dart'
    - 'lib/src/generated/*.dart'
  errors:
    undefined_prefixed_name: ignore
linter:
  rules:
    - public_member_api_docs
